# Use root/admin as user/password credentials
version: "3"

services:
  mongo:
    image: mongo:4.4.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: AlgorithmConfigs
    volumes:
      - ./mocks/dotnetUser.js:/docker-entrypoint-initdb.d/dotnetUser.js
      - ./mocks/configs.js:/docker-entrypoint-initdb.d/configs.js
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
