# Use root/admin as user/password credentials
version: "3"

services:
  mongo:
    image: mongo:4.4.3
    env_file:
      - .env
    volumes:
      - ./mocks/dotnetUser.js:/docker-entrypoint-initdb.d/dotnetUser.js
      - ./mocks/configs.js:/docker-entrypoint-initdb.d/configs.js
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    volumes:
      - ./rabbit/definitions.json:/opt/definitions.json:ro
      - ./rabbit/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
